### ISSUE TITLE
Auto detect composer file defined in sub projects of Workspace

### ISSUE THREAD

**Issue by shivapoudel** [ikappas/vscode-composer#10]
Why there is always need of `composer.workingPath`. Can't we autodetect those file :)

**Comment by bmerigan** [comment]
Upvote!

I have a project containing multiple applications in subdirectories which all share code and each application has it's own composer.json file.

The best way for this to work would be if Composer could be called from a context menu when right-clicking on a composer.json file

**Comment by shivapoudel** [comment]
Switched to vscode-phpsab for this feature!
