### ISSUE TITLE
Validation failure in "repositories"

### ISSUE THREAD

**Issue by samlikins** [ikappas/vscode-composer#14]
In the [Disabling Packagist.org](https://getcomposer.org/doc/05-repositories.md#disabling-packagist-org) section of the Composer documentation, it's specified that the following can be used in the "repositories" section.

```
    {
        "packagist.org": false
    }
```

However, when using this extension, the previous snippet causes two "Missing property" problems; one for `"type"` and the other for `"url"`.  I attempted to locate the JSON schema used in this extension with no luck.  I'm not sure how validation of the `composer.json` file is performed, however this does need to be corrected.

**Comment by ikappas** [comment]
@samlikins To disable packagist.org repositories you should have something like this in your composer.json
```json
    "repositories": [
        {
            "packagist.org": false
        }
    ],
```
Schema validation stopped working at some point but now that version 0.8.0 is out with updated json schema validation it is working again, so I am closing this issue.
