### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by orblazer** [ikappas/vscode-composer#15]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Composer_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).

Additional info:

- This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by paul121** [comment]
I've open a PR to add this to open-vsx: https://github.com/ikappas/vscode-composer

**Comment by ikappas** [comment]
@orblazer @paul121  Version 0.8.0 is out with several fixes which should now be able to compile successfully.

**Comment by ikappas** [comment]
@orblazer @paul121 As the extension is already published on open-vsx I am closing this issue ;) 

See also #23
