### ISSUE TITLE
Extension does not see the open project

### ISSUE THREAD

**Issue by AnrDaemon** [ikappas/vscode-composer#16]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6532485/98464497-5e12b600-21d4-11eb-9feb-abb93f7a0145.png)

Extension version: 0.7.1
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T15:06:15.712Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.96GB (4.24GB free)|
|Process Argv|C:\\Users\\anrdaemon\\Documents\\_PHP\\ext-dl --crash-reporter-id d05c8b79-33ba-42b6-8c5c-db1f4b0e913c|
|Screen Reader|no|
|VM|0%|
</details>

<details>
<summary>Extension configuration</summary>
`"composer.executablePath": "composer.btm"` (User)
`"composer.workingPath": "${workspaceFolder}"` (Workspace)
</details>

**Comment by ikappas** [comment]
@AnrDaemon  Version 0.8.0 is out with several fixes, so I am closing this issue. Please feel free to reopen should you find that the issue still persists.
