### ISSUE TITLE
Composer:Require command

### ISSUE THREAD

**Issue by neoacevedo** [ikappas/vscode-composer#17]
What does exactly the command `Composer:Require`? via command line, I set `composer require vendor/package`  but not else via VSCode command interface.

**Comment by ikappas** [comment]
@neoacevedo The commands where not conditionally enabled  with `composer.enabled` setting which caused the behaviour you described. Version 0.8.0 is out with an update for this condition, so I am closing this issue. Please feel free to reopen should the issue still persists.
