### ISSUE TITLE
Executing: composer install   - Command completed with errors

### ISSUE THREAD

**Issue by hoermann-p** [ikappas/vscode-composer#18]
Whenever I run Composer Update, I get the following in my VSCodeTerminal:

```
Executing: composer install

Command completed with errors.
```

I manually downloaded the schema.json, added it as schema to my composer as:

`    "$schema": "../schema.json",`

As the requested url will show a page with the message that the file was moved.
original url: http://json.schemastore.org/composer
new URL - downloaded: https://raw.githubusercontent.com/composer/composer/master/res/composer-schema.json

It is the first time for me working with VSCode and composers, I think I am missing something fundamentally.

I added the zipfile of the project ( from a udemy course, so should be correct ) that I want to compose.
[MadelineprotoWithMysql.zip](https://github.com/ikappas/vscode-composer/files/6678458/MadelineprotoWithMysql.zip)

How can I debug the situation or what do I have to do in order to get this resolved?

**Comment by ikappas** [comment]
@hoermann-p Version 0.8.0 is out with several fixes, including schema validation, so I am closing this issue. Please feel free to reopen should you find that the issue still persists.
