### ISSUE TITLE
 composer.json schema validation fails; URL incorrect

### ISSUE THREAD

**Issue by aeschli** [ikappas/vscode-composer#19]
Forwarded from https://github.com/microsoft/vscode/issues/126699

Issue Type: <b>Bug</b>

When creating a new composer.json file, the JSON extension fails to validate with the following message:
{
	"resource": "/Users/pedro/Projects/sql-updates/composer.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "768",
	"severity": 4,
	"message": "Problems loading reference 'http://json.schemastore.org/composer': Unable to load schema from 'http://json.schemastore.org/composer': Request vscode/content failed unexpectedly without providing any details.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}
Navigating to that URL directly shows the following error:
"The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

The schema validates correctly per "composer validate" command.

**Comment by mglaman** [comment]
@ikappas will there be a release for the URL fix?
