### ISSUE TITLE
Set Composer working directory

### ISSUE THREAD

**Issue by mexcoder** [ikappas/vscode-composer#2]
will be great to add a config option for changing the composer working directory to an arbitrary folder

**Comment by binary64** [comment]
This would be amazing! I have a large git tree that has many "local" roots for composer.json

The way I tried to get it to work was opened a file within the root of my wanted composer.json, F1 > composer: install > but it complains about no composer.json in the topmost root of the vscode folder.

**Comment by ikappas** [comment]
@binary64 I've planned to implement this as a configuration setting

**Comment by binary64** [comment]
Hrm, won't that cost more work to the user than Terminal > cd to/the/subproject > composer install ? Or am I missing something?

It could be strongly assumed the .php file I have focused is part of the project I wish to operate on.

**Comment by ikappas** [comment]
@mexcoder, @binary64 This has been implemented in the latest `develop` branch. See more details at [README.md](https://github.com/ikappas/vscode-composer#composerworkingpath)

@binary64 Please take a look at the aforementioned README and please open a new ticket if your use case differs.
